name: unito_pandemic_decentralized
description: Academic Purpose Application made by Antonio Cavuoto and Riccardo Sieve.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.3.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    mvc_pattern: ^6.1.3+2
    progress_dialog: ^1.2.4
    intro_slider: ^2.3.1
    floor: ^0.14.0
    hive: ^1.4.2
    hive_flutter: ^0.3.1
    cryptography: ^1.4.1
    nearby_connections: ^1.1.1+1
    http: ^0.12.2
    fluttertoast: ^5.0.1
    flip_card: ^0.4.4
    local_auth: ^0.6.2+3
    modal_bottom_sheet: ^0.2.0+1
    nice_button: ^0.1.7
    intl: ^0.16.1
    clipboard_manager: ^0.0.4
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    #cupertino_icons: ^0.1.3
dependency_overrides:

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: "^0.7.5"
    build_runner: ^1.10.0
    floor_generator: ^0.14.0

flutter_icons:
    android: true
    image_path: "lib/img/bacteria.png"
    adaptive_icon_background: "#9c27b0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true
    fonts:
        - family: OpenSans
          fonts:
              - asset: lib/fonts/OpenSans-Regular.ttf
              - asset: lib/fonts/OpenSans-Italic.ttf
                style: italic

    # To add assets to your application, add an assets section, like this:
    assets:
        - lib/img/bacteria.png
        - lib/img/unito.png
        - lib/img/contacts.png
        - lib/img/medical-mask.png
        - lib/img/boy.png
        - lib/img/virus.png
        - lib/img/quarantine.png
        - lib/img/spread.png
        - lib/img/dna.png
        - lib/img/pharmacy.png
        - lib/img/headache.png
        - lib/img/fever.png
        - lib/img/cough.png
        - lib/img/washing-hands.png
        - lib/img/social-distancing.png
        - lib/img/helper.png
        - lib/img/italy.png
        - lib/img/uk.png
        - lib/img/m1.png
        - lib/img/m2.png
        - lib/img/ai.png
        - lib/img/key.png
        - lib/img/password.png
        - lib/img/infected.png
        - lib/img/ok.png
        - lib/img/contagion.png
        - lib/img/shield.png
        - lib/img/benedict.png
    # To add assets to your application, add an assets section, like this:
    # assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
